# Python for Beginners Course by Google Advanced Data Analytics Certificate


## General Preview of Course Code Snippets

In [1]:
#Define a function
def is_adult(age):
    if age >= 18:
        print("adult")
    else:
        print("minor")

In [2]:
#use is_adult function
age = 40
age2 = 17
is_adult(age)

adult


In [3]:
is_adult(age2)

minor


## Jupyter Notebook
It is an open source web application for creating and sharing documents containing live code, math formulas, visualizations and text.

Notebooks enable data professionals collaborate on data projects and integrate code.

## Object-Oriented Programming(OOP)
Object-oriented programming is a programming system that's based on objects, which can contain both data and code that manipulates the aformentioned data.

The main rationale behind OOP entails having both data and the **methods** that manipulate it within objects, allowing for more organized, accessible and reusbale code.

An **Object** is an instance of a class. An object is a fundamental building block of Python programming language.

A class is the most significant concept of OOP is the class.
A **class** is an object's data type that bundles data and functionality together.

The functionality is described by methods that affect the way data stored in a class behaves when an instnce of the class is created(Object).

**Methods** are functions that belong to a class and typically perform an action or operation.

In [4]:
#Demonstrating a variable(object) belonging to string class, and impact of methods on it
magic = "HOCUS POCUS"
magic
print(type(magic))

<class 'str'>


In [5]:
#using built-in functilaities of string class to chenge behavior of the object created above-magic
magic = magic.swapcase()
magic

'hocus pocus'

In [6]:
#replace some characters in magic 
magic = magic.replace('cus', 'key')
magic

'hokey pokey'

## Dot Notation System
System of accessing methods and attributes of an instance of a class.
As depicted by the:
- swapcase
- replace

Applied on magic variable, an instance of string class.

## Core Python Classes
The main Python classes include:
 - Floats
 - Strings
 - Integers
 - Booleans
 - Lists
 - Dictionaries
 - Tuples
 - Lists
 - Sets
 - Frozensets
 - Functions
 - Ranges 
 - None

## Variables
Variables give meaning to code. They are analogous to nouns.

They point to values. You can also view them as containers that store values of an object.

For example the variable **magic**,  stored the string value, "HOCUS POCUS"

When creating meaningful variables that are easy to reference at a later time, certain variable algorithim questions should be considered:

1. What's the variable's name?
2. What's the variable's type?
3. What's the variable's starting value?

Naming variable is important for yourself and other who will review your code. By naming varaibles, you remind yourseld what data type the variable holds, thus what specific operations would be applicable to that data value.

## Assignment and Expression
Assigining expressions makes your code more concise.

**Assignment**: The process of storing a value in a variable.

**Expression**: A combination of numbers, symbols, or other variables that produce a result when evaluated.



In [7]:
#Assign ages of 5 professional football players in EPL to a list
Players_age = [22, 24, 26, 28, 34]
Players_age

[22, 24, 26, 28, 34]

In [8]:
#Assign maximum age of Players_age list to a new variable called: max_age
max_age = max(Players_age)
max_age

34

In [9]:
#check data type of max_age
type(max_age)

int

In [10]:
#we can reassign the data type of max_age from integer to string by convert max_age variable to string data type
max_age = str(max_age)
max_age

'34'

In [11]:
#We cam also reassogn the value of max_age
max_age = 'ninety nine'
max_age

'ninety nine'

## Naming Restrictions for Variables
1. Variables can only include letters,numbers and underscores
2. Must start with a letter of underscore
3. Keywords should never be used in naming variables. Keywords are special words reserved for special purposes in Python
4. Python is Case-sensitive; capiatlization matters when naming variables. For example, **Great** and **great** are two different variables.
5. Variables cannot include parenthesis

## Functions

A **Function** is a body of reusable code for performing specific processes or tasks.
Several built-in functions in Python that we have used include:
- type(): tells us the data type contained in a variable.
- print(): writes text on the screen
- str(): converts an object into a string

Besides using Python's built-in functions, we can customize our own functions that accept certain inputs and produce output.

To define our own function, keyword ***def** is used at the start of the function block.

In [12]:
#create a function welcoming tourists to Kenya
def jambo(name):
    print("Jambo" + "!" +" " + name + " " "Karibu Kenya")
    print("Hakuna Matata")
    
    


In [13]:
jambo("Bill") #application of the function

Jambo! Bill Karibu Kenya
Hakuna Matata


There are many things we can use to extract value from defined functions.
For exampke we would want to get values out of a funtion.

**return** keyword makes a function produce new results, that are saved for later use.

In [14]:
#defined function that returns values
def area_triangle(base, height):
    area = base * height / 2
    return area

In [15]:
#compute area of triangle
triangle_a = area_triangle(10, 6)
triangle_a

30.0

## Reusability
Custom-defined functions form part of core elements of code reusability.

**Reusability** entails defining code once and using it many times without having to rewrite it.

In [16]:
#define function that computes time in seconds
def get_seconds(hours, minutes, seconds):
    total_seconds = 3600 * hours + 60 * minutes + seconds
    return total_seconds

In [17]:
#compute 18hrs, 40 mins and 30 seconds in seconds
seconds = get_seconds(18, 40, 30)
seconds

67230

Let's review the code below, and see where modular code involving writing reusable code can be applied.
The goal is reducing code duplication  by using functions.

In [18]:
name = "Ogombo"
number = len(name)* 10
print("Hello " + name + ". Your lucky number is " + str(number)) # line similar to the code below

name = "Asega"
number = len(name)* 10
print("Hello " + name + ". Your lucky number is " + str(number)) #similar to the code above


Hello Ogombo. Your lucky number is 60
Hello Asega. Your lucky number is 50


In [19]:
#write a function that groups duplicated code into one line
def lucky_number(name):
    number = len(name) * 10
    print("Hello " + name + ". Your lucky number is " + str(number))
    
#use fucntion on two new names
lucky_number("Matrix")
lucky_number("Daredevil")



Hello Matrix. Your lucky number is 60
Hello Daredevil. Your lucky number is 90


## Modularity
Modularity refers to ability to write code in seperate components that work together and that can be reused for other programs.

## Refactoring
Refactoring is the process of restructuring code while maintaining its original functionality. 

The goal of refactoring involves creating self-documenting code. Self-documenting code is code written in a way that is readable and makes its purpose clear.

### Comments
Helpful suplemental explaination of the code.

In [20]:
# Function takes an integer as input and returns its factorial
def factorial(n):
    #Exclude 0 as a prouct, start with 1
    y = 1
    for i in range(int(n)):
        y = y*(i + 1)
    return y

# Enter a numerical value between 1-9 in the command line that appears
input_num = input() 

# Apply factorial function to an integer input
print(factorial(input_num))

4
24


## Writing Algorithimic Code

An *Algorithim* is a set of instructions that solve a problem or execute a task.

At the heart of any hardware or software architecture is an algorithim that provides logic to the computer on how to execute tasks.

Using comments as a blue print for building algorithimc code improves the fow of executing a complex algorithim.

If you were to build a complex function, breaking it into small, simple pieces would enable you to tackle a problem that is to be solved by the function.

## Docstring

Docstring is a string at the beginning of a function's body that summarizes the function's behavior and explain its arguments and return values.

In [21]:
#function for computing profit_margin

def profit_margin(net_profit, revenue):
    """ 
    Calculate the profit margin earned by a company.
    
        Parameters:
            net_profit(float): net earnings generated by a company in dollars
            revenue(float): sales earned by a company in dollars
        Returns:
            profit_margin(float): profit_margin represented as (net_profit / revenue) in percentage, rounded off to 2 decimal places.
    
    """
    profit_margin = round(float(net_profit) / float(revenue), 2)
    return profit_margin

In [22]:
net_profit = 2000
revenue = 20000
earnings_margin = profit_margin(net_profit, revenue)
earnings_margin

0.1

In [23]:
#check documetation of profit_margin function
help(profit_margin)

Help on function profit_margin in module __main__:

profit_margin(net_profit, revenue)
    Calculate the profit margin earned by a company.
    
        Parameters:
            net_profit(float): net earnings generated by a company in dollars
            revenue(float): sales earned by a company in dollars
        Returns:
            profit_margin(float): profit_margin represented as (net_profit / revenue) in percentage, rounded off to 2 decimal places.



## Comparison Operators
Comparison operators  are operators that compare two values and produce boolean values(**True** or **False**).

Types of Comparators(comparison operators) in Python include:
- Greater than: >
- Greater than or equal to: >=
- Less than: <
- Less than or equal to: <=
- Equal to: ==
- Not equal to: !=

In [24]:
30 > 1

True

In [25]:
50 < 49.9

False

In [26]:
print("cat" == "Elephant")

False


## Logical Operators
Operators that connect multiple statements together and perform more complex operations.

Types of Logical operators in Python include:
- and : Both expression of operation to be true to return a **True** result
- or  : Expression will be true if either of the expression is **True**, and **False** only whe both expressions are **False**.
- not : Inverts the value of the expression that follow it. If its true, it becomes false and vice versa.

In [27]:
#evaluate and operator
expression = 20 < 4 and 40 > 20
print(expression)

expression2 = "cat" < "dog" and "egg" > "ant"
print(expression2)

False
True


In [28]:
#evaluate or operator
expression3 = 20 < 4 or 40 > 20
print(expression3)

True


In [29]:
#evaluate not operator
print(not 100 > 1000)

True


## Branching/ Control Structures

Branching refers to the ability of a program to alter its execution sequence.
Branching uses **if** statements based on certain conditions

**if** is a reserved keyword that sets up a condition in Python.

The if statement is usually bundled with **else** statement.

**else** is a reserved keyword that executes when preceding conditions (of if statemnt) evaluate as False.


In [30]:
#create a function that aunthenticates valid username by restricting it to eight characters.
def hint_username(username):
    if len(username) < 8:
        print("Invalid username. Must be at least 8 characters long.")
    else:
        print("Valid Username. ")

In [31]:
user = "collins"
hint_username(user)

Invalid username. Must be at least 8 characters long.


In [32]:
10 % 2


0

## Loops

Loops are used to automate repetitive tasks in Python.

Loops automatically repeat a portion of code until a process is complete.

In a nutshell, a **loop** is a block of code used to carry out interations.

**Iterable**: object that's looped, or, interated over. It can be a string, list, dictionary etc.

Data professionals use **while loops** and **for loops** to iterate iterables.

**while loops**: a loop that commands your computer to continously execute your code based on the value of a condition.

A **for loop**: piece of codes that interates over a sequence of values(iterable).

In [33]:
# while loop example
y = 0
while y < 4:
    print("value of y is " + str(y))
    y = y + 1
    
print(y)

value of y is 0
value of y is 1
value of y is 2
value of y is 3
4


In [34]:
# for loop example
for n in range(6):
    print(n)

0
1
2
3
4
5


In [35]:
#factorial of nine using for loops
product = 1
for n in range(1, 10):
    product = product * n

print(product)

362880


## Data Types in Python

###  Strings
Strings are a sequence of characters and puntuations that contain textual information.

Strings are immutable data structures in python usually presented as characters in quotes.
 
They can be concatenated and multiplied.

**Escape character**: represented as \, it's a character that changes the typical behaviour of the characters that follow it.

In [36]:
#concatenation of strings

movie = "Black Panther Forever"

release = " was releases in 2023. It was a mega hit, grossing over a billion dollars."

movie_release = movie + release
print(movie_release)

Black Panther Forever was releases in 2023. It was a mega hit, grossing over a billion dollars.


In [37]:
#multiplication of strings
movie_release_perception = "OMG "
movie_release_perception * 3

'OMG OMG OMG '

In [38]:
# showing quotes in sring characters
applause = '"The movie was just awesome"'
print(applause)

"The movie was just awesome"


In [39]:
#uses of escape character
quote = "\"It's okay not to be okay!\""
print(quote)

"It's okay not to be okay!"


In [40]:
#use backslash character with n to print a new line when printing a string
bond = "My name is Bond,\n James Bond!"
print(bond)

My name is Bond,
 James Bond!


In [41]:
#use for loops to iterate over strings
Thor = "mjolnyr"
for thor in Thor:
    print("I love " + thor)

I love m
I love j
I love o
I love l
I love n
I love y
I love r


## Indexing

Indexing is a way to refer to individual items within an iterable by their relative position.

Indexing is a very important concept in Python as it allows us to :
- select data
- filter data
- edit data
- manipulate data

Python uses zero-based indexing.

### String Methods
1. index(): string method that outputs the index number of a character in a string.
2. format(): formats and inserts specific substrings into designated places within a larger string.

In [42]:
## find index of 't' in the following string
sport = "football"
sport.index('t')

3

In [43]:
#access character at index 5
sport[5]

'a'

In [44]:
# slice sport string
sport[1:4]

'oot'

In [45]:
fruit = "apple"
fruit[:3]

'app'

In [46]:
#check mebership of string in a given variable/string characters
print("banana" in sport)

print("apple" in fruit)

False
True


In [47]:
#use format string method
role = "Junior data analyst"
salary = 2000
print("In september 2023, I will starting a new role, {} with a monthly salary of ${}.".format(role, salary))

In september 2023, I will starting a new role, Junior data analyst with a monthly salary of $2000.


In [48]:
#Another example of using format string method
price = 12.5
with_tax = price * 1.25

print("Base price: ${:.2f} USD. \nwith_tax: ${:.2f} USD.".format(price, with_tax))

Base price: $12.50 USD. 
with_tax: $15.62 USD.


## Data Structures

Data structures are a collection of data values or objects that contain different data types.

Data structures are used to store, organize and categorize data. Data professionals use them for speed and efficiency.

### Types of Data Structures in Python
a) **List**

A list is a data structure that helps store and manipulate an ordered collection of items. List store sequence of ordered elements. They allow duplicate elements. 

Lists also allow indexing and sequencing.

A **sequence** is a positionally ordered collection of items.

 Lists are mutable
 
 Common methods applicable to lists:
 - append(): adds an element to the end of a list as a single new entry.
 - insert(): takes and index as the first parameter and an element as the second parameter, then inserts the element into a list at the given index.
 - remove(): remove an element in a list

In [49]:
#create a list
marvel = ["Iron Man", "Thor", "Spider Man", "Doctor Strange", "Daredevil"]

#index the list
marvel[2]

'Spider Man'

In [50]:
#slice the list
marvel[2:4]

['Spider Man', 'Doctor Strange']

In [51]:
marvel[3:]

['Doctor Strange', 'Daredevil']

In [52]:
#add another brand to the brands list
tech_brands = ["Google", "Microsoft", "Meta", "Netflix", "Nvidia"]
tech_brands

['Google', 'Microsoft', 'Meta', 'Netflix', 'Nvidia']

In [53]:
tech_brands.append("Twitter")
print(tech_brands)

['Google', 'Microsoft', 'Meta', 'Netflix', 'Nvidia', 'Twitter']


In [54]:
#insert snapchat into the 3 position of tech_brands list
tech_brands.insert(2, "Snapchat")
print(tech_brands)

['Google', 'Microsoft', 'Snapchat', 'Meta', 'Netflix', 'Nvidia', 'Twitter']


In [55]:
#remove 'Netflix' from the tech_brands list
tech_brands.remove("Netflix")
print(tech_brands)

['Google', 'Microsoft', 'Snapchat', 'Meta', 'Nvidia', 'Twitter']


 ### Tuple
 
 A **tuple** is an immutable sequence that can contain elements of any data type.

In [56]:
#instatiate a tuple of my full name
fullname = tuple(("Collins", "Ogombo", "Ochiko"))
print(fullname)


('Collins', 'Ogombo', 'Ochiko')


In [57]:
#convert tech_brands into a tuple
brands = tuple(tech_brands)
print(brands)

('Google', 'Microsoft', 'Snapchat', 'Meta', 'Nvidia', 'Twitter')


In [58]:
#tuples used to return values and functions

def to_dollars_cents(price):
    '''
        Split price(float) into dollars and cents
    '''
    dollars = int(price // 1)
    cents = round(price % 1 * 100)
    
    return dollars, cents

In [59]:
to_dollars_cents(9.55)

(9, 55)

In [60]:
#unpack a tuple into two  seperate variable
dollars, cents = to_dollars_cents(12.88)
print(dollars - 1)
print(cents - 10)

11
78


In [61]:
best_players = [("Christiano Ronaldo", 7, "Forward"),
                ("Luis Suarez", 8, "Right wing"),
               ("Lionel Messi", 10, "Forward"),
               ("Sergio Busquets", 14, "Center Back")]
print(best_players)

[('Christiano Ronaldo', 7, 'Forward'), ('Luis Suarez', 8, 'Right wing'), ('Lionel Messi', 10, 'Forward'), ('Sergio Busquets', 14, 'Center Back')]


In [62]:
for name, number, position in best_players:
    print(name, number)

Christiano Ronaldo 7
Luis Suarez 8
Lionel Messi 10
Sergio Busquets 14


In [63]:
for player in best_players:
    print(player[0])

Christiano Ronaldo
Luis Suarez
Lionel Messi
Sergio Busquets


In [64]:
def player_rank(players):
    result = []
    for name, rank, position in players:
        result.append('name: {:>20} \nposition: {:>15}\n'.format(name, position))
    
    return result

In [65]:
player_rank(best_players)

['name:   Christiano Ronaldo \nposition:         Forward\n',
 'name:          Luis Suarez \nposition:      Right wing\n',
 'name:         Lionel Messi \nposition:         Forward\n',
 'name:      Sergio Busquets \nposition:     Center Back\n']

In [66]:
#use the results of the function in a for loop
for player in player_rank(best_players):
    print(player)

name:   Christiano Ronaldo 
position:         Forward

name:          Luis Suarez 
position:      Right wing

name:         Lionel Messi 
position:         Forward

name:      Sergio Busquets 
position:     Center Back



## Dictionaries

A dictionary is a data structure that consists of a collection of key-value pairs.

Dictionary methods:

1. keys(): retrieve only the keys of the ditionary
2. values(): retrieve only the dictionary's values
3. items(): retrieve both keys and values of a dictionary

In [70]:
#example dictionary

careers = {
    'year1': 'BI Analyst',
    'year2': 'Product Analyst',
    'year3': 'Business Analyst'
} 

print(careers)

{'year1': 'BI Analyst', 'year2': 'Product Analyst', 'year3': 'Business Analyst'}


In [71]:
#Access elements of 'careers' dictionary
careers['year1']

'BI Analyst'

In [76]:
#add another element in the dictionary
careers['year4'] = "Product Manager"
print(careers)

{'year1': 'BI Analyst', 'year2': 'Product Analyst', 'year3': 'Business Analyst', 'year4': 'Product Manager'}


In [74]:
#another example of dictionary using dict function

my_goals = dict(
q1='Payment of School fees for Brighton',
q2='Travel to SA/Zanzibar',
q3='Purchase land upcountryside',
q4='Buy tuxedo for Dad')

print(my_goals)


{'q1': 'Payment of School fees for Brighton', 'q2': 'Travel to SA/Zanzibar', 'q3': 'Purchase land upcountryside', 'q4': 'Buy tuxedo for Dad'}


In [80]:
#define a list tuples of data analytics:language, specialisation and Job Role.
data_analytics = [
    ("Python", "Machine Learning", "ML Engineer"),
    ("SQL", "Database Design", "DB Administrator"),
    ("R", "Data Science", "Data Scientist"),
    ("Power BI", "Data Visualization", "BI Developer"),
    ("Python", "Data Analysis", "Data Analyst"),
    ("R", "Data Visualization", "Viz Expert"),
    ("Scala", "Big Data", "Big Data Specialist")
]

#instantiate an empty dictionary
analytics_requirements = {}

#loop over each tuple in data _analytics list, extract the language, and assign it as a dictionary key;
#extract speacialisation and job role as a list of tuple annd assign them as a tuple within a slist representing the value of the dictionary.
for language, specialisation, role in data_analytics:
    if language in analytics_requirements:
        analytics_requirements[language].append((specialisation, role))
    else:
        analytics_requirements[language] = [(specialisation, role)]
        
analytics_requirements

{'Python': [('Machine Learning', 'ML Engineer'),
  ('Data Analysis', 'Data Analyst')],
 'SQL': [('Database Design', 'DB Administrator')],
 'R': [('Data Science', 'Data Scientist'),
  ('Data Visualization', 'Viz Expert')],
 'Power BI': [('Data Visualization', 'BI Developer')],
 'Scala': [('Big Data', 'Big Data Specialist')]}

In [82]:
print(analytics_requirements["Python"])

print(analytics_requirements["Power BI"])

[('Machine Learning', 'ML Engineer'), ('Data Analysis', 'Data Analyst')]
[('Data Visualization', 'BI Developer')]


In [83]:
#access keys of dictionary

analytics_requirements.keys()

dict_keys(['Python', 'SQL', 'R', 'Power BI', 'Scala'])

In [86]:
#access values of dictionary

print(careers.values())

analytics_requirements.values()

dict_values(['BI Analyst', 'Product Analyst', 'Business Analyst', 'Product Manager'])


dict_values([[('Machine Learning', 'ML Engineer'), ('Data Analysis', 'Data Analyst')], [('Database Design', 'DB Administrator')], [('Data Science', 'Data Scientist'), ('Data Visualization', 'Viz Expert')], [('Data Visualization', 'BI Developer')], [('Big Data', 'Big Data Specialist')]])

In [87]:
#access both values and keys of careers dictionary
careers.items()

dict_items([('year1', 'BI Analyst'), ('year2', 'Product Analyst'), ('year3', 'Business Analyst'), ('year4', 'Product Manager')])

In [88]:
for a, b in analytics_requirements.items():
    print(a, b)

Python [('Machine Learning', 'ML Engineer'), ('Data Analysis', 'Data Analyst')]
SQL [('Database Design', 'DB Administrator')]
R [('Data Science', 'Data Scientist'), ('Data Visualization', 'Viz Expert')]
Power BI [('Data Visualization', 'BI Developer')]
Scala [('Big Data', 'Big Data Specialist')]


## Sets

Sets are python data structures that contain unordered , non-interchangeable elements.

Each set element is **unique and immutable**. However, the set itself is mutable.

Sets are valuable when storing mixed data in a single row/record in a  data table.

To create a set, use **set()** function.

**set()** : takes an iterable(list, tuple,string) as an argument and returns a new set object.

Additional functions one can use on sets:
1. intersection(): finds the elements that two sets have in common
2. union(): finds all elements from both sets
3. difference(): finds elements present in one set, but not the other.
4. symmetric_difference: finds elements from both sets that are mutually not present in the other.

In [90]:
#set example

#breakfast list
breakfast = ["cereal", "milk", "banana", "eggs"]
breakfast_set = set(breakfast)

print(breakfast_set)

{'banana', 'eggs', 'milk', 'cereal'}


In [91]:
#set example 2: using tuple
planets = ("earth", "mars", "mars", "jupiter","venus", "venus")
planets_set = set(planets)

print(planets_set) #output contains only unique elements

{'earth', 'venus', 'jupiter', 'mars'}


In [93]:
#find intersetion of the two sets

set_a = {12, 14, 16, 18, 20, 22, 25}
set_b = {12, 16, 20, 26, 28}

print(set_a.intersection(set_b))

print(set_a & set_b) #use of ampersand operator

{16, 20, 12}
{16, 20, 12}


In [96]:
#find union of two sets

confectionerry = {"cake", "biscuits", "scorns", "croissant"}
bagels = {"croissant", "bun", "scorns", "bread"}

print(confectionerry.union(bagels))

print(confectionerry | bagels) #unio operator symbol

{'biscuits', 'croissant', 'bun', 'cake', 'scorns', 'bread'}
{'biscuits', 'croissant', 'bun', 'cake', 'scorns', 'bread'}


In [98]:
#find difference in two sets
print(confectionerry.difference(bagels))

print(confectionerry - bagels)

{'biscuits', 'cake'}
{'biscuits', 'cake'}


In [99]:
#find symmetric difference between two sets

print(confectionerry.symmetric_difference(bagels))

{'biscuits', 'bun', 'cake', 'bread'}


## Packages

Library/package refers to a reusable collection of code.
It also contains related modules and documentation.

Modules: python files that contain a colletion of funtions and global variables

Commonly used libraries for data work are:

1. matplotlib: library fpr creating static, animated and interactive visualizations in Python 
2. seaborn: data visualization library based on matplotlib that provides a simpler interface for working with common plots and graphs.
3. Numpy: library that contains multidimensional array and matrix data structures and functions to manipulate them. Commonly used for scientific computation.
4. Pandas: Built on top of Numpy. It is used to manipulate and analyze tabular data.

## Numpy

Numpy's power comes from vectorization.

Vectorization enables operations to be performed on multiple components of a data object at the same time.

### n-dimensional array(ndarray)
The array is the core data object of numpy.
The ndarray is a vector

1. ndarrays are mutable;you can change the values they contain.
2. All elements of ndarray should be of the same data type
3. dtype: A numpy attribute used to check the data type of the contents of an array.


In [101]:
#pefrom a vectorized computation


import numpy as np

#create two lists
list_a = [2, 4, 6, 8]
list_b = [1, 2, 3, 4]

#convert the two lists into arrays
array_a = np.array(list_a)
array_b = np.array(list_b)

#multiply the two arrays

array_a * array_b

array([ 2,  8, 18, 32])

In [102]:
type(array_a)

numpy.ndarray

In [106]:
x = np.array([10, 20, 30])
x

array([10, 20, 30])

In [108]:
#change a value in x array
x[-1] = 40
x

array([10, 20, 40])

In [127]:
x[2] = 30
x

array([10, 20, 30])

In [115]:
y = np.array([2, 2.5, 'sell'])
y #output is coerced into one data type

array(['2', '2.5', 'sell'], dtype='<U32')

In [118]:
#check data type of elements of x  and y array
print(x.dtype)

print(y.dtype)

int32
<U32


In [125]:
#create multi-dimension array

muiti_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])
print(f"The shape of array is: {muiti_array.shape}") 
print(f"Number of dimensions of array is: {muiti_array.ndim}")

print(muiti_array)

The shape of array is: (4, 3)
Number of dimensions of array is: 2
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [130]:
#reshape the array to 4 rows, 2 columns
new_array = muiti_array.reshape(3, 4)
new_array

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [132]:
#numpy functions
average = np.mean(new_array)
average

65.0

In [136]:
print(np.floor(5.9))

print(np.ceil(3.1))

5.0
4.0


## Pandas

Pandas is used to analyze and manipulate tabular data. 

Tabular data is in the form of a table, with rows and columns.

The 2 core data structure of pandas are:
- Dataframe: two-dimensional labeled data structure with rows and columns.
- Series: a one-dimensional labeled array

Pandas methods:
- agg(): A pandas groupby method that allows you to apply multiple calculations to groups of data.

In [141]:
# import pandas library

import pandas as pd

#create d adataframe
data = {"months": [1,2,3,4,5,6,7,8,9,10], "sales": [10,20,30,40,50,60,70,80,90,100]}
data_frame = pd.DataFrame(data)
data_frame

months  sales
0       1     10
1       2     20
2       3     30
3       4     40
4       5     50
5       6     60
6       7     70
7       8     80
8       9     90
9      10    100

In [146]:
data_frame.describe()

months       sales
count  10.00000   10.000000
mean    5.50000   55.000000
std     3.02765   30.276504
min     1.00000   10.000000
25%     3.25000   32.500000
50%     5.50000   55.000000
75%     7.75000   77.500000
max    10.00000  100.000000

In [148]:
#select series from row/column of data_frame
print(type(data_frame.iloc[1]) 

months     2
sales     20
Name: 1, dtype: int64


In [144]:
#using ndarray, create another dataframe

sales_array = np.array([[100, 200, 300, 400, 500],[200, 400, 600, 800, 1000]])
columns = ['jan', 'feb', 'mar', 'apr', 'may']
index = range(2)
df = pd.DataFrame(data=sales_array, columns=columns, index=index)
print(df)

   jan  feb  mar  apr   may
0  100  200  300  400   500
1  200  400  600  800  1000


In [151]:
cd


C:\Users\user


In [154]:
#load csv file
path = "products.csv"
products = pd.read_csv(path)
products.head() #inspect the dataset

Product_ID      Product_Name Product_Category Product_Cost Product_Price
0           1     Action Figure             Toys       $9.99        $15.99 
1           2    Animal Figures             Toys       $9.99        $12.99 
2           3   Barrel O' Slime     Art & Crafts       $1.99         $3.99 
3           4  Chutes & Ladders            Games       $9.99        $12.99 
4           5  Classic Dominoes            Games       $7.99         $9.99

In [155]:
#inspect columns of products dataset

products.columns

Index(['Product_ID', 'Product_Name', 'Product_Category', 'Product_Cost',
       'Product_Price'],
      dtype='object')

In [159]:
#check number of columns and rows contained in products dataset

print(f"number of rows is:{products.shape[0]} and number of columns is: {products.shape[1]}")

number of rows is:35 and number of columns is: 5


In [160]:
#summary information about the dataset
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Product_ID        35 non-null     int64 
 1   Product_Name      35 non-null     object
 2   Product_Category  35 non-null     object
 3   Product_Cost      35 non-null     object
 4   Product_Price     35 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.5+ KB


In [162]:
#return a series object of a column 
products['Product_Cost'].head()

0    $9.99 
1    $9.99 
2    $1.99 
3    $9.99 
4    $7.99 
Name: Product_Cost, dtype: object

In [165]:
#using iloc to select rows and columns by index
products.iloc[[0]] #first row selected

Product_ID   Product_Name Product_Category Product_Cost Product_Price
0           1  Action Figure             Toys       $9.99        $15.99

In [168]:
#slice rows based on iloc
products.iloc[:4] #select top 4 rows

Product_ID      Product_Name Product_Category Product_Cost Product_Price
0           1     Action Figure             Toys       $9.99        $15.99 
1           2    Animal Figures             Toys       $9.99        $12.99 
2           3   Barrel O' Slime     Art & Crafts       $1.99         $3.99 
3           4  Chutes & Ladders            Games       $9.99        $12.99

In [172]:
#subset of rows and columns
products.iloc[:6, 0:2] #top 6 rows and top 2 columns

Product_ID      Product_Name
0           1     Action Figure
1           2    Animal Figures
2           3   Barrel O' Slime
3           4  Chutes & Ladders
4           5  Classic Dominoes
5           6         Colorbuds

In [173]:
#select all rows for the first 3 columns
products.iloc[:, 0:3]

Product_ID           Product_Name   Product_Category
0            1          Action Figure               Toys
1            2         Animal Figures               Toys
2            3        Barrel O' Slime       Art & Crafts
3            4       Chutes & Ladders              Games
4            5       Classic Dominoes              Games
5            6              Colorbuds        Electronics
6            7               Dart Gun  Sports & Outdoors
7            8          Deck Of Cards              Games
8            9               Dino Egg               Toys
9           10       Dinosaur Figures               Toys
10          11          Etch A Sketch       Art & Crafts
11          12     Foam Disk Launcher  Sports & Outdoors
12          13       Gamer Headphones        Electronics
13          14          Glass Marbles              Games
14          15      Hot Wheels 5-Pack               Toys
15          16                  Jenga              Games
16          17        Kids Makeup Kit       Art & Crafts
17          18            Lego Bricks               Toys
18          19             Magic Sand       Art & Crafts
19          20   Mini Basketball Hoop  Sports & Outdoors
20          21     Mini Ping Pong Set  Sports & Outdoors
21          22               Monopoly              Games
22          23         Mr. Potatohead               Toys
23          24               Nerf Gun  Sports & Outdoors
24          25            PlayDoh Can       Art & Crafts
25          26        PlayDoh Playset       Art & Crafts
26          27        PlayDoh Toolkit       Art & Crafts
27          28               Playfoam       Art & Crafts
28          29             Plush Pony               Toys
29          30           Rubik's Cube              Games
30          31           Splash Balls  Sports & Outdoors
31          32  Supersoaker Water Gun  Sports & Outdoors
32          33             Teddy Bear               Toys
33          34              Toy Robot        Electronics
34          35          Uno Card Game              Games

In [189]:
#convert Product_Cost and Product_Price into float data type

products["Product_Cost"] = products["Product_Cost"].replace("$", "") #remove dollar sign
products["Product_Cost"] = products["Product_Cost"].astype('float')
products["Product_Cost"].dtype

dtype('float64')

In [204]:
products["Product_Price"] = products["Product_Price"].replace("$", "")#remove dollar sign
products["Product_Price"] = products["Product_Price"].astype('float')
products["Product_Price"].dtype 
products.head()

Product_ID      Product_Name Product_Category  Product_Cost  Product_Price
0           1     Action Figure             Toys          9.99          15.99
1           2    Animal Figures             Toys          9.99          12.99
2           3   Barrel O' Slime     Art & Crafts          1.99           3.99
3           4  Chutes & Ladders            Games          9.99          12.99
4           5  Classic Dominoes            Games          7.99           9.99

In [205]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Product_ID        35 non-null     int64  
 1   Product_Name      35 non-null     object 
 2   Product_Category  35 non-null     object 
 3   Product_Cost      35 non-null     float64
 4   Product_Price     35 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 1.5+ KB


In [206]:
products.describe()

Product_ID  Product_Cost  Product_Price
count   35.000000     35.000000      35.000000
mean    18.000000     10.247143      14.761429
std     10.246951      6.563459       7.491508
min      1.000000      1.990000       2.990000
25%      9.500000      5.490000       9.990000
50%     18.000000      9.990000      12.990000
75%     26.500000     12.990000      19.990000
max     35.000000     34.990000      39.990000

## Boolean Masking

**Boolean masking**: filtering technique that overlays a Boolean grid onto a dataframe in order to select only the values in the dataframe that align with the True values of the grid.

In [208]:
#create a boolean mask of 'Product_Price' less than 20
price_mask = products["Product_Price"] < 20
price_mask.head()

0    True
1    True
2    True
3    True
4    True
Name: Product_Price, dtype: bool

In [213]:
#use price_mask to filter out the data
price_less_20 = products[price_mask]
price_less_20



Product_ID           Product_Name   Product_Category  Product_Cost  \
0            1          Action Figure               Toys          9.99   
1            2         Animal Figures               Toys          9.99   
2            3        Barrel O' Slime       Art & Crafts          1.99   
3            4       Chutes & Ladders              Games          9.99   
4            5       Classic Dominoes              Games          7.99   
5            6              Colorbuds        Electronics          6.99   
6            7               Dart Gun  Sports & Outdoors         11.99   
7            8          Deck Of Cards              Games          3.99   
8            9               Dino Egg               Toys          9.99   
9           10       Dinosaur Figures               Toys         10.99   
11          12     Foam Disk Launcher  Sports & Outdoors          8.99   
13          14          Glass Marbles              Games          5.99   
14          15      Hot Wheels 5-Pack               Toys          3.99   
15          16                  Jenga              Games          2.99   
16          17        Kids Makeup Kit       Art & Crafts         13.99   
18          19             Magic Sand       Art & Crafts         13.99   
20          21     Mini Ping Pong Set  Sports & Outdoors          6.99   
21          22               Monopoly              Games         13.99   
22          23         Mr. Potatohead               Toys          4.99   
23          24               Nerf Gun  Sports & Outdoors         14.99   
24          25            PlayDoh Can       Art & Crafts          1.99   
26          27        PlayDoh Toolkit       Art & Crafts          3.99   
27          28               Playfoam       Art & Crafts          3.99   
28          29             Plush Pony               Toys          8.99   
29          30           Rubik's Cube              Games         17.99   
30          31           Splash Balls  Sports & Outdoors          7.99   
31          32  Supersoaker Water Gun  Sports & Outdoors         11.99   
32          33             Teddy Bear               Toys         10.99   
34          35          Uno Card Game              Games          3.99   

    Product_Price  
0           15.99  
1           12.99  
2            3.99  
3           12.99  
4            9.99  
5           14.99  
6           15.99  
7            6.99  
8           10.99  
9           14.99  
11          11.99  
13          10.99  
14           5.99  
15           9.99  
16          19.99  
18          15.99  
20           9.99  
21          19.99  
22           9.99  
23          19.99  
24           2.99  
26           4.99  
27          10.99  
28          19.99  
29          19.99  
30           8.99  
31          14.99  
32          12.99  
34           7.99

In [218]:
#Using tilde function, filter out products with prices higher than 20
price_more_20 = products[~price_mask]
price_more_20

Product_ID          Product_Name   Product_Category  Product_Cost  \
10          11         Etch A Sketch       Art & Crafts         10.99   
12          13      Gamer Headphones        Electronics         14.99   
17          18           Lego Bricks               Toys         34.99   
19          20  Mini Basketball Hoop  Sports & Outdoors          8.99   
25          26       PlayDoh Playset       Art & Crafts         20.99   
33          34             Toy Robot        Electronics         20.99   

    Product_Price  
10          20.99  
12          20.99  
17          39.99  
19          24.99  
25          24.99  
33          25.99

In [229]:
#select products whose cost is more than 15 and price is more than 18
price_cost_mask = (products["Product_Cost"] > 15) & (products["Product_Price"] > 18)
price_cost_mask

products_price_cost = products[price_cost_mask]
products_price_cost

Product_ID     Product_Name Product_Category  Product_Cost  Product_Price
17          18      Lego Bricks             Toys         34.99          39.99
25          26  PlayDoh Playset     Art & Crafts         20.99          24.99
29          30     Rubik's Cube            Games         17.99          19.99
33          34        Toy Robot      Electronics         20.99          25.99

In [253]:
#add profit column
products["Product_Profit"] = products["Product_Price"] - products["Product_Cost"]
products[["Product_Profit"]]
products.head()

Product_ID      Product_Name Product_Category  Product_Cost  Product_Price  \
0           1     Action Figure             Toys          9.99          15.99   
1           2    Animal Figures             Toys          9.99          12.99   
2           3   Barrel O' Slime     Art & Crafts          1.99           3.99   
3           4  Chutes & Ladders            Games          9.99          12.99   
4           5  Classic Dominoes            Games          7.99           9.99   

   Product_Profit  
0             6.0  
1             3.0  
2             2.0  
3             3.0  
4             2.0

In [231]:
#acsertain product categories

products['Product_Category'].value_counts()

Toys                 9
Art & Crafts         8
Games                8
Sports & Outdoors    7
Electronics          3
Name: Product_Category, dtype: int64

In [247]:
#Use groupby to find sum of all values in porduct cost and product price for each category in descending order
products.groupby("Product_Category")[["Product_Price", "Product_Cost"]].sum().sort_values(by="Product_Price", ascending=False)

Product_Price  Product_Cost
Product_Category                              
Toys                      143.91        104.91
Sports & Outdoors         106.93         71.93
Art & Crafts              104.92         71.92
Games                      98.92         66.92
Electronics                61.97         42.97

In [255]:
#group proucts by category and calculate both average and median profit
profit_by_category = products.groupby("Product_Category")["Product_Profit"].agg(["mean", "median"])
profit_by_category

mean  median
Product_Category                   
Art & Crafts       4.125000     3.0
Electronics        6.333333     6.0
Games              4.000000     3.5
Sports & Outdoors  5.000000     3.0
Toys               4.333333     4.0

## Pandas Function

1. concat(): combines data either by adding it horizontally as new columns for existing rows, or vertically as new rows for existing columns.
2. merge(): joins tow dataframe together; it only combines data by extending along axis one horizontally.

## The End

Feel free to visist Coursera to learn more about the course: **Google Advanced Data Analytics Certificate**